// The wallet adapter's stylesheet, minus its import of a Google font: that request would break
// the site's Content Security Policy (and tell Google about every visitor). The wallet buttons use
// the site's own font instead. `walletCss.test.ts` regenerates this from the installed package, so
// an upgrade that changes the upstream file cannot leave the copy stale.

export const FONT_IMPORT = /^@import url\('https:\/\/fonts\.googleapis\.com\/[^']*'\);\s*\n/m
export const UPSTREAM_FONT = /'DM Sans', 'Roboto', 'Helvetica Neue', Helvetica, Arial, sans-serif/g
export const SITE_FONT = 'var(--font-geist-sans), system-ui, sans-serif'

/// The notice the Apache-2.0 license asks a modified copy to carry.
export const NOTICE = `/*
 * Generated by app/scripts/wallet-css.mts from styles.css of @solana/wallet-adapter-react-ui
 * (https://github.com/anza-xyz/wallet-adapter), licensed under the Apache License 2.0.
 * Modified: the Google font import is removed and the site's own font is used instead.
 */
`

export function localWalletCss(upstream: string): string {
    return NOTICE + upstream.replace(FONT_IMPORT, '').replace(UPSTREAM_FONT, SITE_FONT)
}
