const FONT_IMPORT = /^@import url\('https:\/\/fonts\.googleapis\.com\/[^']*'\);\s*\n/m
const UPSTREAM_FONT = /'DM Sans', 'Roboto', 'Helvetica Neue', Helvetica, Arial, sans-serif/g
const SITE_FONT = 'var(--font-geist-sans), system-ui, sans-serif'

export const NOTICE = `/*
 * Generated by app/scripts/wallet-css.mts from styles.css of @solana/wallet-adapter-react-ui
 * (https://github.com/anza-xyz/wallet-adapter), licensed under the Apache License 2.0.
 * Modified: the Google font import is removed and the site's own font is used instead.
 */
`

export function localWalletCss(upstream: string): string {
    return NOTICE + upstream.replace(FONT_IMPORT, '').replace(UPSTREAM_FONT, SITE_FONT)
}
